from decouple import config

TEMPFILES_PATH=config("TEMPFILES_PATH")   
FILE_LIFETIME_DAYS=config("FILE_LIFETIME_DAYS", cast=int)

ALL_INVOICES_PATH=config("ALL_INVOICES_PATH")
INVOICES_APP_PATH=config("INVOICES_APP_PATH")
INVOICES_EXCEL_PATH=config("INVOICES_EXCEL_PATH")

PRODUCT_PATH=config("PRODUCT_PATH")
CHROME_DRIVER_PATH=config("CHROME_DRIVER_PATH")
PRODUCTS_EXCEL_PATH=config("PRODUCTS_EXCEL_PATH")
EMAIL=config("EMAIL")
PASS=config("PASS")
BUDGET=config("BUDGET", cast=float)

LOG_PATH=config("LOG_PATH")
MIN_LOG_LEVEL=config("MIN_LOG_LEVEL")